language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - genesis.jz.93@gmail.com
      - doblesesays@outlook.com
    on_success: always
    on_failure:  always
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy of the project"
  on:
    branch: master